let suggestions =["Channel",
"CodingLab",
"CodingIndia",
"Youtube",
"Youtuber",
"Youtube Channel",
"Blogger",
"Bollywood",
"Vlogger",
"Vechiles",
"Facebook",
"Freelancer",
"Facebook Page",
"Designer",
"Developer",
"Web Designer",
"Web Developer",
"Login form in HTML & CSS",
"How to learn HTML & CSS",
"How to learn Javascript",
"How to became Freelancer",
"How to became Web Designer",
"How to start Gaming Channel",
"How to start YouTube Channel",
"How does HTML stands for?",
"What does CSS stands for?",];